Update navbar title on auth details screen
aerogear/ios-showcase-template pull request #38
Opened 2018-06-18 15:19 UTC by aidenkeating

Allow the root nav bar to be updated when the auth details page is shown instead of the auth login page.

https://docs.google.com/presentation/d/1FZL-Wy5D_wUo5ADrfhpRBh-Ny2rGauI3_C8SBrlk6rw/edit#slide=id.g3c52d834c7_0_72

2018-06-18 15:31 UTC, aidenkeating commented
@wei-lee Mind taking a look?

2018-06-18 15:48 UTC, wei-lee commented on ios-showcase-template/authentication/AuthenticationRouter.swift
> +    public static let PAGE_IDENTITY_PROFILE_TITLE = "Identity Profile"
is this used anywhere?

2018-06-18 15:54 UTC, wei-lee commented on ios-showcase-template/authentication/AuthenticationRouter.swift
> +            self.options.titleViewController.title = options.authDetailsNavigationTitle
better use `self.options.something` to keep it consistent.

2018-06-18 15:55 UTC, wei-lee requested changes
see my comments.

2018-06-18 15:55 UTC, ciaranRoche reviewed
Was it decided to remove `Email Verified` from the app? If so might be worth doing it in this PR.

2018-06-19 08:02 UTC, aidenkeating commented
@wei-lee Comments addressed.

@ciaranRoche Not sure. @wei-lee Has removing the `Email Verified` (and I guess the `2FA section`) been decided? If so, I'll probably do it in a separate PR.

2018-06-19 08:33 UTC, wei-lee commented
@aidenkeating I will let you know as soon as I got confirmation. In the meantime, we can leave it for now and remove it later in a separate PR.

2018-06-20 10:01 UTC, wei-lee approved these changes

2018-06-20 10:12 UTC, ciaranRoche approved these changes
Looks good to merge, keep the other change for a different PR

2018-06-20 10:48 UTC, merged